name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          if ! command -v cmake &> /dev/null; then
            brew install cmake
          fi

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" ..
          make -j$(sysctl -n hw.ncpu)

      - name: Ad-hoc Signing
        run: |
          codesign --force --deep --sign - "build/ReharmStudio_artefacts/Reharm Studio.app"

      - name: Clear Extended Attributes
        run: |
          xattr -cr "build/ReharmStudio_artefacts/Reharm Studio.app"

      - name: Create ZIP
        run: |
          ditto -ck --keepParent "build/ReharmStudio_artefacts/Reharm Studio.app" "ReharmStudio.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: ReharmStudio.zip
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
